// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/auth-redesign/CountryPicker.tsx": () => import("../components/mockups/auth-redesign/CountryPicker.tsx"),
  "./components/mockups/auth-redesign/Current.tsx": () => import("../components/mockups/auth-redesign/Current.tsx"),
  "./components/mockups/auth-redesign/PalRobot.tsx": () => import("../components/mockups/auth-redesign/PalRobot.tsx"),
  "./components/mockups/auth-reference/Login.tsx": () => import("../components/mockups/auth-reference/Login.tsx"),
  "./components/mockups/auth-reference/Register.tsx": () => import("../components/mockups/auth-reference/Register.tsx"),
  "./components/mockups/account-page/AccountReference.tsx": () => import("../components/mockups/account-page/AccountReference.tsx"),
  "./components/mockups/account-page/AccountScreenshot.tsx": () => import("../components/mockups/account-page/AccountScreenshot.tsx"),
  "./components/mockups/checkin-game/Current.tsx": () => import("../components/mockups/checkin-game/Current.tsx"),
  "./components/mockups/checkin-game/CurrentVisual.tsx": () => import("../components/mockups/checkin-game/CurrentVisual.tsx"),
  "./components/mockups/checkin-game/FortuneWheelDesign.tsx": () => import("../components/mockups/checkin-game/FortuneWheelDesign.tsx"),
  "./components/mockups/checkin-redesign/Current.tsx": () => import("../components/mockups/checkin-redesign/Current.tsx"),
  "./components/mockups/checkin-redesign/ReferenceMatch.tsx": () => import("../components/mockups/checkin-redesign/ReferenceMatch.tsx"),
  "./components/mockups/home-welcome-popup/Current.tsx": () => import("../components/mockups/home-welcome-popup/Current.tsx"),
  "./components/mockups/home-welcome-popup/ReferenceMatch.tsx": () => import("../components/mockups/home-welcome-popup/ReferenceMatch.tsx"),
  "./components/mockups/invitation-page/Current.tsx": () => import("../components/mockups/invitation-page/Current.tsx"),
  "./components/mockups/invitation-page/InviteReference.tsx": () => import("../components/mockups/invitation-page/InviteReference.tsx"),
  "./components/mockups/revenue-page/Current.tsx": () => import("../components/mockups/revenue-page/Current.tsx"),
  "./components/mockups/revenue-page/ReferenceMatch.tsx": () => import("../components/mockups/revenue-page/ReferenceMatch.tsx"),
  "./components/mockups/service-client-page/Current.tsx": () => import("../components/mockups/service-client-page/Current.tsx"),
  "./components/mockups/service-client-page/FrenchMatch.tsx": () => import("../components/mockups/service-client-page/FrenchMatch.tsx"),
  "./components/mockups/share-team/Current.tsx": () => import("../components/mockups/share-team/Current.tsx"),
  "./components/mockups/share-team/LevelDetails.tsx": () => import("../components/mockups/share-team/LevelDetails.tsx"),
  "./components/mockups/share-team/ShareReference.tsx": () => import("../components/mockups/share-team/ShareReference.tsx"),
  "./components/mockups/transaction-history-cards/Current.tsx": () => import("../components/mockups/transaction-history-cards/Current.tsx"),
  "./components/mockups/transaction-history-cards/ReferenceMatch.tsx": () => import("../components/mockups/transaction-history-cards/ReferenceMatch.tsx")
};
